ALTER TABLE books ALTER COLUMN isbn TYPE VARCHAR (20);
ALTER TABLE books ADD COLUMN language VARCHAR NOT NULL DEFAULT 'English';
ALTER TABLE books ADD COLUMN description TEXT;
ALTER TABLE books DROP COLUMN genre;
ALTER TABLE books ADD COLUMN genres text[] NOT NULL DEFAULT ARRAY['None'];